In [1]:
# Install scQuint
!pip install -U git+https://github.com/songlab-cal/scquint.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/songlab-cal/scquint.git
  Cloning https://github.com/songlab-cal/scquint.git to /tmp/pip-req-build-jzxqivup
  Running command git clone -q https://github.com/songlab-cal/scquint.git /tmp/pip-req-build-jzxqivup
Collecting anndata
  Downloading anndata-0.8.0-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 3.0 MB/s
Collecting scanpy
  Downloading scanpy-1.9.1-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 41.8 MB/s
Requirement already satisfied: networkx in /usr/local/lib/python3.7/dist-packages (from scquint==0.2) (2.6.3)
Requirement already satisfied: torch in /usr/local/lib/python3.7/dist-packages (from scquint==0.2) (1.11.0+cu113)
Collecting pyro-ppl
  Downloading pyro_ppl-1.8.1-py3-none-any.whl (718 kB)
     |████████████████████████████████| 718 kB 44.6 MB/s
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from scquint==0.2) (1.0.2)
Collecting snakemake
  Downloading snakemake-7.8.1.tar.gz (302 kB)
     |████████████████████████████████| 302 kB 71.7 MB/s
Requirement already satisfied: statsmodels in /usr/local/lib/python3.7/dist-packages (from scquint==0.2) (0.10.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from scquint==0.2) (1.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from scquint==0.2) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from scquint==0.2) (1.3.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from scquint==0.2) (1.4.1)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.7/dist-packages (from anndata->scquint==0.2) (21.3)
Requirement already satisfied: natsort in /usr/local/lib/python3.7/dist-packages (from anndata->scquint==0.2) (5.5.0)
Requirement already satisfied: importlib_metadata>=0.7 in /usr/local/lib/python3.7/dist-packages (from anndata->scquint==0.2) (4.11.4)
Requirement already satisfied: h5py>=3 in /usr/local/lib/python3.7/dist-packages (from anndata->scquint==0.2) (3.1.0)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.7/dist-packages (from anndata->scquint==0.2) (4.2.0)
Requirement already satisfied: cached-property in /usr/local/lib/python3.7/dist-packages (from h5py>=3->anndata->scquint==0.2) (1.5.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib_metadata>=0.7->anndata->scquint==0.2) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20->anndata->scquint==0.2) (3.0.9)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->scquint==0.2) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->scquint==0.2) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->scquint==0.2) (1.15.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.7/dist-packages (from pyro-ppl->scquint==0.2) (3.3.0)
Requirement already satisfied: tqdm>=4.36 in /usr/local/lib/python3.7/dist-packages (from pyro-ppl->scquint==0.2) (4.64.0)
Collecting pyro-api>=0.1.1
  Downloading pyro_api-0.1.2-py3-none-any.whl (11 kB)
Collecting session-info
  Downloading session_info-1.0.0.tar.gz (24 kB)
Requirement already satisfied: patsy in /usr/local/lib/python3.7/dist-packages (from scanpy->scquint==0.2) (0.5.2)
Collecting umap-learn>=0.3.10
  Downloading umap-learn-0.5.3.tar.gz (88 kB)
     |████████████████████████████████| 88 kB 7.4 MB/s
Requirement already satisfied: numba>=0.41.0 in /usr/local/lib/python3.7/dist-packages (from scanpy->scquint==0.2) (0.51.2)
Collecting matplotlib>=3.4
  Downloading matplotlib-3.5.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
     |████████████████████████████████| 11.2 MB 39.4 MB/s
Requirement already satisfied: seaborn in /usr/local/lib/python3.7/dist-packages (from scanpy->scquint==0.2) (0.11.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.4->scanpy->scquint==0.2) (1.4.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.4->scanpy->scquint==0.2) (0.11.0)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.33.3-py3-none-any.whl (930 kB)
     |████████████████████████████████| 930 kB 56.8 MB/s
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.4->scanpy->scquint==0.2) (7.1.2)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /usr/local/lib/python3.7/dist-packages (from numba>=0.41.0->scanpy->scquint==0.2) (0.34.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from numba>=0.41.0->scanpy->scquint==0.2) (57.4.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->scquint==0.2) (3.1.0)
Collecting pynndescent>=0.5
  Downloading pynndescent-0.5.7.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 50.5 MB/s
Collecting stdlib_list
  Downloading stdlib_list-0.8.0-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 2.2 MB/s
Requirement already satisfied: wrapt in /usr/local/lib/python3.7/dist-packages (from snakemake->scquint==0.2) (1.14.1)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from snakemake->scquint==0.2) (2.23.0)
Collecting ratelimiter
  Downloading ratelimiter-1.2.0.post0-py3-none-any.whl (6.6 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from snakemake->scquint==0.2) (3.13)
Collecting configargparse
  Downloading ConfigArgParse-1.5.3-py3-none-any.whl (20 kB)
Requirement already satisfied: appdirs in /usr/local/lib/python3.7/dist-packages (from snakemake->scquint==0.2) (1.4.4)
Collecting datrie
  Downloading datrie-0.8.2-cp37-cp37m-manylinux1_x86_64.whl (537 kB)
     |████████████████████████████████| 537 kB 59.3 MB/s
Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from snakemake->scquint==0.2) (4.3.3)
Requirement already satisfied: docutils in /usr/local/lib/python3.7/dist-packages (from snakemake->scquint==0.2) (0.17.1)
Collecting gitpython
  Downloading GitPython-3.1.27-py3-none-any.whl (181 kB)
     |████████████████████████████████| 181 kB 73.7 MB/s
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from snakemake->scquint==0.2) (5.4.8)
Requirement already satisfied: nbformat in /usr/local/lib/python3.7/dist-packages (from snakemake->scquint==0.2) (5.4.0)
Collecting toposort
  Downloading toposort-1.7-py2.py3-none-any.whl (9.0 kB)
Collecting connection_pool>=0.0.3
  Downloading connection_pool-0.0.3.tar.gz (3.8 kB)
Collecting pulp>=2.0
  Downloading PuLP-2.6.0-py3-none-any.whl (14.2 MB)
     |████████████████████████████████| 14.2 MB 50.1 MB/s
Requirement already satisfied: smart_open>=3.0 in /usr/local/lib/python3.7/dist-packages (from snakemake->scquint==0.2) (6.0.0)
Collecting stopit
  Downloading stopit-1.1.2.tar.gz (18 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from snakemake->scquint==0.2) (0.8.9)
Collecting yte<2.0,>=1.0
  Downloading yte-1.5.1-py3-none-any.whl (7.5 kB)
Collecting jinja2<4.0,>=3.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 58.0 MB/s
Collecting retry
  Downloading retry-0.9.2-py2.py3-none-any.whl (8.0 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.7/dist-packages (from jinja2<4.0,>=3.0->snakemake->scquint==0.2) (2.0.1)
Collecting pyyaml
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 36.5 MB/s
Collecting dpath<3.0,>=2.0
  Downloading dpath-2.0.6-py3-none-any.whl (15 kB)
Collecting plac<2.0.0,>=1.3.4
  Downloading plac-1.3.5-py2.py3-none-any.whl (22 kB)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.9-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 1.7 MB/s
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->snakemake->scquint==0.2) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->snakemake->scquint==0.2) (21.4.0)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->snakemake->scquint==0.2) (5.7.1)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/dist-packages (from nbformat->snakemake->scquint==0.2) (4.10.0)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.7/dist-packages (from nbformat->snakemake->scquint==0.2) (5.1.1)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.7/dist-packages (from nbformat->snakemake->scquint==0.2) (2.15.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->snakemake->scquint==0.2) (2022.5.18.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->snakemake->scquint==0.2) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->snakemake->scquint==0.2) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->snakemake->scquint==0.2) (1.24.3)
Requirement already satisfied: decorator>=3.4.2 in /usr/local/lib/python3.7/dist-packages (from retry->snakemake->scquint==0.2) (4.4.2)
Requirement already satisfied: py<2.0.0,>=1.4.26 in /usr/local/lib/python3.7/dist-packages (from retry->snakemake->scquint==0.2) (1.11.0)
Building wheels for collected packages: scquint, umap-learn, pynndescent, session-info, snakemake, connection-pool, stopit
  Building wheel for scquint (setup.py) ... done
  Created wheel for scquint: filename=scquint-0.2-py3-none-any.whl size=8920 sha256=d8d382cf93e18357ab2191ed49e46cb3b9263ab7feacee6cf0a13c3ba2a6d6a9
  Stored in directory: /tmp/pip-ephem-wheel-cache-01axtvju/wheels/60/7a/bd/1dacc7a9d14b27f14a92016878aebcf4ce97a532d46a31d20b
  Building wheel for umap-learn (setup.py) ... done
  Created wheel for umap-learn: filename=umap_learn-0.5.3-py3-none-any.whl size=82829 sha256=2d9f7a5c4176153e23bbf3c26341608622982edcbb8bc2a9fa85c74f9ad9ceb4
  Stored in directory: /root/.cache/pip/wheels/b3/52/a5/1fd9e3e76a7ab34f134c07469cd6f16e27ef3a37aeff1fe821
  Building wheel for pynndescent (setup.py) ... done
  Created wheel for pynndescent: filename=pynndescent-0.5.7-py3-none-any.whl size=54286 sha256=532e9b7d4a315ed145eb9fb8795f1aafe8138f299adf7a30616125e7c6066253
  Stored in directory: /root/.cache/pip/wheels/7f/2a/f8/7bd5dcec71bd5c669f6f574db3113513696b98f3f9b51f496c
  Building wheel for session-info (setup.py) ... done
  Created wheel for session-info: filename=session_info-1.0.0-py3-none-any.whl size=8048 sha256=ae2655fedcb8cef4a22b27599ddbec52775c36ddbd56a2807620d07655a15bd5
  Stored in directory: /root/.cache/pip/wheels/bd/ad/14/6a42359351a18337a8683854cfbba99dd782271f2d1767f87f
  Building wheel for snakemake (setup.py) ... done
  Created wheel for snakemake: filename=snakemake-7.8.1-py3-none-any.whl size=334491 sha256=fbcc6fea499c27e7d6d434b3c26d30d07ee1b45552ef2c3416fe5ab30ef6d622
  Stored in directory: /root/.cache/pip/wheels/a9/7b/9d/e599e33efb84272c1bd485e3fa8aff68ac727f203c9d3e0d13
  Building wheel for connection-pool (setup.py) ... done
  Created wheel for connection-pool: filename=connection_pool-0.0.3-py3-none-any.whl size=4084 sha256=85e821efff90a17ab6bf0c8825f07b1f41fba431921e4144be9f6de8cb6f4acd
  Stored in directory: /root/.cache/pip/wheels/a0/66/fa/93d22c4aed2fcf82f4d7a0ab8587cb3e1918153471360f8e07
  Building wheel for stopit (setup.py) ... done
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11956 sha256=ceab1e707292f312f3c7bcff0a0699ec711354070609d2321ceb493f717c0b2f
  Stored in directory: /root/.cache/pip/wheels/e2/d2/79/eaf81edb391e27c87f51b8ef901ecc85a5363dc96b8b8d71e3
Successfully built scquint umap-learn pynndescent session-info snakemake connection-pool stopit
Installing collected packages: smmap, fonttools, stdlib-list, pyyaml, pynndescent, plac, matplotlib, gitdb, dpath, yte, umap-learn, toposort, stopit, session-info, retry, ratelimiter, pyro-api, pulp, jinja2, gitpython, datrie, connection-pool, configargparse, anndata, snakemake, scanpy, pyro-ppl, scquint
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Attempting uninstall: plac
    Found existing installation: plac 1.1.3
    Uninstalling plac-1.1.3:
      Successfully uninstalled plac-1.1.3
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 2.11.3
    Uninstalling Jinja2-2.11.3:
      Successfully uninstalled Jinja2-2.11.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 7.4.0 requires plac<1.2.0,>=0.9.6, but you have plac 1.3.5 which is incompatible.
spacy 2.2.4 requires plac<1.2.0,>=0.9.6, but you have plac 1.3.5 which is incompatible.
flask 1.1.4 requires Jinja2<3.0,>=2.10.1, but you have jinja2 3.1.2 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed anndata-0.8.0 configargparse-1.5.3 connection-pool-0.0.3 datrie-0.8.2 dpath-2.0.6 fonttools-4.33.3 gitdb-4.0.9 gitpython-3.1.27 jinja2-3.1.2 matplotlib-3.5.2 plac-1.3.5 pulp-2.6.0 pynndescent-0.5.7 pyro-api-0.1.2 pyro-ppl-1.8.1 pyyaml-6.0 ratelimiter-1.2.0.post0 retry-0.9.2 scanpy-1.9.1 scquint-0.2 session-info-1.0.0 smmap-5.0.0 snakemake-7.8.1 stdlib-list-0.8.0 stopit-1.1.2 toposort-1.7 umap-learn-0.5.3 yte-1.5.1

In [1]:
# Download processed intron count dat
!wget https://figshare.com/ndownloader/files/27696714 -O adata_spl.h5ad

--2022-06-08 03:13:30--  https://figshare.com/ndownloader/files/27696714
Resolving figshare.com (figshare.com)... 54.72.163.193, 52.50.42.102, 2a05:d018:1f4:d000:7421:2135:71b2:6a10, ...
Connecting to figshare.com (figshare.com)|54.72.163.193|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/27696714/adata_spl.h5ad?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIYCQYOYV5JSSROOA/20220608/eu-west-1/s3/aws4_request&X-Amz-Date=20220608T031330Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=fa6a714d2ec76df88d02f677647b3ec25922882f636430fd2cc20aa9fb69d172 [following]
--2022-06-08 03:13:30--  https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/27696714/adata_spl.h5ad?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIYCQYOYV5JSSROOA/20220608/eu-west-1/s3/aws4_request&X-Amz-Date=20220608T031330Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=fa6a714d2ec76df88d02f677647b3ec25922882f636430fd2cc20aa9fb69d172
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 52.218.46.96
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.218.46.96|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 286049939 (273M) [application/octet-stream]
Saving to: ‘adata_spl.h5ad’

adata_spl.h5ad      100%[===================>] 272.80M  30.5MB/s    in 9.7s

2022-06-08 03:13:41 (28.3 MB/s) - ‘adata_spl.h5ad’ saved [286049939/286049939]

In [2]:
import anndata
import numpy as np

from scquint.differential_splicing import run_differential_splicing

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [3]:
adata = anndata.read_h5ad("adata_spl.h5ad")
adata

AnnData object with n_obs × n_vars = 44518 × 29965
    obs: 'FACS.selection', 'age', 'cell', 'cell_ontology_class', 'cell_ontology_id', 'free_annotation', 'method', 'mouse.id', 'sex', 'subtissue', 'tissue', 'n_genes', 'n_counts', 'louvain', 'leiden', 'cell_type', 'plate_id'
    var: 'chromosome', 'start', 'end', 'cluster', 'left_exon_count', 'left_genes', 'right_exon_count', 'right_genes', 'genes', 'n_genes', 'genes_cluster', 'n_genes_cluster', 'annotated', 'gene_id', 'original_cluster', 'n_start', 'strand', 'cluster_type'

In [4]:
adata.obs[adata.obs.tissue=="Heart"].cell_ontology_class.value_counts()[:10]

fibroblast of cardiac tissue           2118
endothelial cell of coronary artery    1179
monocyte                                490
endocardial cell                        164
atrial myocyte                          159
valve cell                              158
smooth muscle cell                       65
ventricular myocyte                      46
T cell                                   37
B cell                                   15
Name: cell_ontology_class, dtype: int64

In [5]:
# Specify the indices of the two groups to be compared
cell_idx_a = np.where((adata.obs.tissue=="Heart") & (adata.obs.cell_ontology_class=="endocardial cell"))[0]
cell_idx_b = np.where((adata.obs.tissue=="Heart") & (adata.obs.cell_ontology_class=="atrial myocyte"))[0]
len(cell_idx_a), len(cell_idx_b)

(164, 159)

In [6]:
clusters, introns = run_differential_splicing(
    adata, cell_idx_a, cell_idx_b, min_cells_per_cluster=50, min_total_cells_per_intron=50, n_jobs=1,
)

sample sizes:  164 159
(323, 29965)
filter_min_cells_per_feature
filter_singletons
(323, 271)
filter_min_global_proportion
filter_singletons
(323, 271)
filter_min_cells_per_cluster
filter_singletons
filter_min_cells_per_cluster
filter_singletons
(323, 169)
Number of intron clusters:  84
Number of introns:  169
Testing intron cluster  0

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5516: ImplicitModificationWarning: Trying to modify attribute `.var` of view, initializing view as actual.
  self[name] = value
/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5516: ImplicitModificationWarning: Trying to modify attribute `.var` of view, initializing view as actual.
  self[name] = value
/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5516: ImplicitModificationWarning: Trying to modify attribute `.var` of view, initializing view as actual.
  self[name] = value
/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5516: ImplicitModificationWarning: Trying to modify attribute `.var` of view, initializing view as actual.
  self[name] = value

Done

In [7]:
# clusters has information about all the intron clusters that were tested
clusters.head()

,p_value,ll_null,ll,n_classes,gene_id,gene_name,max_abs_delta_psi,max_abs_lfc_psi,ranking,p_value_adj
cluster,,,,,,,,,,
0,2.783505e-47,-358.71158349144565,-254.41451957203446,2,ENSMUSG00000061904,NA,0.803164,29.571781,0,2.338144e-45
40,5.241887e-41,-304.4620056272593,-214.54001975380993,2,ENSMUSG00000032366,NA,0.803828,3.785967,1,2.201593e-39
20,4.590732e-39,-452.07306917411984,-366.59853066480963,2,ENSMUSG00000025781,NA,0.723182,2.771993,2,1.285405e-37
33,1.121661e-36,-250.61923551606782,-170.61056985779743,2,ENSMUSG00000008892,NA,0.798089,6.172689,3,2.355488e-35
48,1.605253e-30,-118.71941662337022,-52.78925329732763,2,ENSMUSG00000018845,NA,0.900812,5.421720,4,2.696825e-29

In [8]:
# introns has information about all the introns corresponding to the tested clusters
introns.head()

,chromosome,start,end,cluster,left_exon_count,left_genes,right_exon_count,right_genes,genes,n_genes,...,n_start,strand,cluster_type,psi_a,psi_b,delta_psi,lfc_psi,abs_delta_psi,abs_lfc_psi,gene_name
0,chr10,91119707,91121922,0,9,['ENSMUSG00000061904'],5,['ENSMUSG00000061904'],['ENSMUSG00000061904'],1,...,1,-,shared_acceptor,1.000000e+00,0.196836,0.803164,2.344936,0.803164,2.344936,NA
1,chr10,91119707,91122207,0,9,['ENSMUSG00000061904'],2,['ENSMUSG00000061904'],['ENSMUSG00000061904'],1,...,1,-,shared_acceptor,6.494021e-12,0.803164,-0.803164,-29.571781,0.803164,29.571781,NA
2,chr10,128491034,128491720,1,11,['ENSMUSG00000090841'],1,['ENSMUSG00000090841'],['ENSMUSG00000090841'],1,...,1,-,shared_acceptor,7.666660e-01,0.206015,0.560651,1.895847,0.560651,1.895847,NA
3,chr10,128491034,128492059,1,11,['ENSMUSG00000090841'],14,['ENSMUSG00000090841'],['ENSMUSG00000090841'],1,...,1,-,shared_acceptor,2.333340e-01,0.793985,-0.560651,-1.766715,0.560651,1.766715,NA
4,chr11,4702221,4703904,2,4,['ENSMUSG00000059534'],2,['ENSMUSG00000059534'],['ENSMUSG00000059534'],1,...,1,-,shared_acceptor,3.145444e-02,0.102419,-0.070964,-1.703142,0.070964,1.703142,NA

In [9]:
# Number of significant differential splicing events
(clusters.p_value_adj < 0.05).sum()

45

In [10]:
# The introns belonging to the intron cluster with the lowest p-value
introns[introns.cluster==0]

,chromosome,start,end,cluster,left_exon_count,left_genes,right_exon_count,right_genes,genes,n_genes,...,n_start,strand,cluster_type,psi_a,psi_b,delta_psi,lfc_psi,abs_delta_psi,abs_lfc_psi,gene_name
0,chr10,91119707,91121922,0,9,['ENSMUSG00000061904'],5,['ENSMUSG00000061904'],['ENSMUSG00000061904'],1,...,1,-,shared_acceptor,1.000000e+00,0.196836,0.803164,2.344936,0.803164,2.344936,NA
1,chr10,91119707,91122207,0,9,['ENSMUSG00000061904'],2,['ENSMUSG00000061904'],['ENSMUSG00000061904'],1,...,1,-,shared_acceptor,6.494021e-12,0.803164,-0.803164,-29.571781,0.803164,29.571781,NA

In [ ]:
# The results can be visualized with 
# the cellxgene browser https://scquint.ds.czbiohub.org/tabula-muris/
# and UCSC Genome Browser https://genome.ucsc.edu/s/gbenegas/tabulamuris